yatube/posts/urls.py
from django.urls import path

from . import views


app_name = "posts"

urlpatterns = [
    # Главная страница
    path("", views.index, name="index"),
    # Отдельная страница с информацией о group
    path("group/<slug:slug>/", views.group_posts, name="group_list"),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("posts.urls", namespace="posts")),
]

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Group(models.Model):
    title = models.CharField("имя", max_length=200)
    slug = models.SlugField("адрес", unique=True)
    description = models.TextField("описание")

    class Meta:
        verbose_name = "Groups, it will be shown in admin panel"

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField("заголовок")
    pub_date = models.DateTimeField("дата публикации", auto_now_add=True)
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name="posts",
        verbose_name="сообщество",
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="posts",
        verbose_name="автор",
    )

    def __str__(self):
        return self.text

    class Meta:
        verbose_name = "Posts, it will be shown in admin panel"
        ordering = ["-pub_date"]

yatube/posts/views.py
from django.shortcuts import render, get_object_or_404

# Импортируем модель, чтобы обратиться к ней
from .models import Post, Group


def index(request):
    posts = Post.objects.all()[:10]
    title = "Последние обновления на сайте"
    # В словаре context отправляем информацию в шаблон
    context = {
        "posts": posts,
        "title": title,
    }
    return render(request, "posts/index.html", context)


# View-функция для страницы сообщества:
def group_posts(request, slug):
    # Функция get_object_or_404 получает по заданным критериям объект
    # из базы данных или возвращает ошибк, если объект не найден.
    # В нашем случае в group будут переданы объекты модели Group,
    # поле slug у которых соответствует значению slug в запросе
    group = get_object_or_404(Group, slug=slug)

    # Метод .filter позволяет ограничить поиск по критериям.
    # Это аналог добавления
    # условия WHERE group_id = {group_id}
    posts = Post.objects.filter(group=group)[:10]
    title = "Записи сообщества"
    context = {
        "group": group,
        "posts": posts,
        "title": title,
    }
    return render(request, "posts/group_list.html", context)

yatube/templates/base.html
<!DOCTYPE html> 
<html lang="ru">          
  <head>
    {% load static %}
    <meta charset="utf-8"> <!-- Кодировка сайта -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="img/fav/fav.ico" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="img/fav/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="img/fav/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="img/fav/favicon-16x16.png">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"> 
    <title>
      {% block title %}
        Title не подвезли :(
      {% endblock %}
    </title>           
  </head>
  <body>       
    <header>
      {% include 'includes/header.html' %}
    </header>
    <main>
      {% block content %}
        Контент не подвезли :(
      {% endblock %}
    </main>
    <footer class="border-top text-center py-3">
      {% include 'includes/footer.html' %} 
    </footer>
  </body>
</html>

yatube/templates/includes/footer.html
<p>© 2021 Copyright <span style="color:red">Ya</span>tube</p> 

yatube/templates/includes/header.html
{% load static %}
<nav class="navbar navbar-light" style="background-color: lightskyblue">
        <div class="container">
          <a class="navbar-brand" href="{% url 'posts:index' %}">
            <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
            <span style="color:red">Ya</span>tube</a>
          </a>
        </div>
      </nav>  

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %}
  {{ title }}
{% endblock %}
{% block content %}
  <div class="container py-5">
    <h1>{{ title }} {{ group }}</h1>
    {% for post in posts %}
      <ul>
        <li>
          Автор: {{ post.author.get_full_name }}
        </li>
        <li>
           Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
      </ul>
      <p>{{ post.text }}</p>
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %} 
  </div>  
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %}
  {{ title }}
{% endblock %}
{% block content %}
  <div class="container py-5">     
    <h1>{{ title }}</h1>
      {% for post in posts %}
        <ul>
          <li>
            Автор: {{ post.author.get_full_name }}
          </li>
          <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
        </ul>
        <p>
          {{ post.text }}
        </p>
        {% if post.group %}  
          <a href="{%url 'posts:group_list' post.group.slug %}">все записи группы</a>
        {% endif %}  
        {% if not forloop.last %}<hr>{% endif %}
      {% endfor %}
    </div>  
{% endblock %}